#!/usr/bin/env ruby
# ^ The above comment tells the system
# to read this file like a ruby file
require_relative '../lib/dbc_today/controller'

phase = ARGV[0]
week = ARGV[1]
day = ARGV[2] || Date.today.wday.to_s

controller = Controller.new

controller.show_schedule(phase, week, day)